-- Persist presentation groups independently of column slugs and calculation dependencies.
ALTER TABLE public.gradebooks ADD CONSTRAINT gradebooks_id_class_id_key UNIQUE (id, class_id);

CREATE TABLE public.gradebook_column_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    class_id bigint NOT NULL,
    gradebook_id bigint NOT NULL,
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    CONSTRAINT gradebook_column_groups_gradebook_fkey FOREIGN KEY (gradebook_id, class_id)
        REFERENCES public.gradebooks (id, class_id) ON DELETE CASCADE,
    CONSTRAINT gradebook_column_groups_scope_key UNIQUE (id, gradebook_id, class_id)
);
CREATE INDEX gradebook_column_groups_gradebook_idx ON public.gradebook_column_groups (gradebook_id, class_id);

ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;
ALTER TABLE public.gradebook_columns ADD CONSTRAINT gradebook_columns_group_fkey
    FOREIGN KEY (group_id, gradebook_id, class_id)
    REFERENCES public.gradebook_column_groups (id, gradebook_id, class_id);
CREATE INDEX gradebook_columns_group_idx ON public.gradebook_columns (group_id, gradebook_id, class_id);
COMMENT ON COLUMN public.gradebook_columns.group_id IS
    'Optional presentation group. Unassigned columns render individually. Unassign members before deleting a group.';

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gradebook_column_groups TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gradebook_column_groups_id_seq TO authenticated, service_role;
CREATE POLICY "instructors manage groups" ON public.gradebook_column_groups
    FOR ALL TO authenticated
    USING (public.authorizeforclassinstructor(class_id))
    WITH CHECK (public.authorizeforclassinstructor(class_id));
CREATE POLICY "course members read groups" ON public.gradebook_column_groups
    FOR SELECT TO authenticated USING (public.authorizeforclass(class_id));

-- Staff receive group edits through the same course controller as column edits.
CREATE TRIGGER broadcast_gradebook_column_groups
    AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.broadcast_course_table_change_unified();

-- Bootstrap only: used by this migration and by the local seed after it creates columns.
-- No INSERT/UPDATE trigger infers membership. Once initialized, names and slugs are independent.
-- Deliberately invoker-security and service-role-only; never exposed to course users.
CREATE FUNCTION public.initialize_gradebook_column_groups(p_gradebook_id bigint)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE
    col record;
    previous_prefix text;
    previous_order integer := -1;
    current_group_id bigint;
    display_name text;
BEGIN
    -- Serialize bootstrap calls for one gradebook. Re-running is a no-op.
    PERFORM 1 FROM public.gradebooks WHERE id = p_gradebook_id FOR UPDATE;
    IF EXISTS (SELECT 1 FROM public.gradebook_column_groups WHERE gradebook_id = p_gradebook_id) THEN
        RETURN;
    END IF;
    FOR col IN
        SELECT c.*,
            CASE WHEN split_part(c.slug, '-', 1) = 'assignment'
                      AND array_length(string_to_array(c.slug, '-'), 1) >= 3
                 THEN 'assignment-' || split_part(c.slug, '-', 2)
                 ELSE coalesce(nullif(split_part(c.slug, '-', 1), ''), 'other') END AS prefix
        FROM public.gradebook_columns c WHERE c.gradebook_id = p_gradebook_id
        ORDER BY coalesce(c.sort_order, 0), c.id
    LOOP
        IF current_group_id IS NULL OR col.prefix IS DISTINCT FROM previous_prefix
            OR (previous_order <> -1 AND coalesce(col.sort_order, 0) <> previous_order + 1) THEN
            display_name := CASE WHEN col.prefix LIKE 'assignment-%'
                THEN split_part(col.prefix, '-', 2) ELSE col.prefix END;
            -- The legacy heuristic permits an empty assignment subtype; give it a usable label.
            display_name := coalesce(nullif(display_name, ''), 'Other');
            display_name := upper(left(display_name, 1)) || substr(display_name, 2);
            INSERT INTO public.gradebook_column_groups (class_id, gradebook_id, name)
                VALUES (col.class_id, col.gradebook_id, display_name) RETURNING id INTO current_group_id;
        END IF;
        UPDATE public.gradebook_columns SET group_id = current_group_id WHERE id = col.id;
        previous_prefix := col.prefix;
        previous_order := coalesce(col.sort_order, 0);
    END LOOP;
END;
$$;
REVOKE ALL ON FUNCTION public.initialize_gradebook_column_groups(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_gradebook_column_groups(bigint) TO service_role;

-- Column updates use the existing audit trigger; ensure today's partition exists first.
SELECT public.audit_maintain_partitions();
SELECT public.initialize_gradebook_column_groups(id) FROM public.gradebooks;
